name: "Monotrack CLI"
description: "Runs Monotrack CLI"
author: ArnoldVanN

inputs:
  command:
    description: "The command to run. Defaults to 'tag bump'"
    default: "tag bump"
  base:
    description: "The base SHA used to compare"
    required: false
  head:
    description: "The HEAD SHA used to compare"
    required: false
  args:
    description: "Arguments to pass to the command"
    required: false
  config:
    description: "Name of the configuration file"
    required: false

outputs:
  output:
    description: "The CLI output"

branding:
  icon: book-open
  color: gray-dark

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.base }}
    - ${{ inputs.head }}
    - ${{ inputs.args }}
    - ${{ inputs.config }}
